return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.17.1",
  orientation = "orthogonal",
  renderorder = "left-up",
  width = 16,
  height = 12,
  tilewidth = 82,
  tileheight = 82,
  nextobjectid = 36,
  properties = {},
  tilesets = {
    {
      name = "ladrilho2",
      firstgid = 1,
      tilewidth = 82,
      tileheight = 82,
      spacing = 0,
      margin = 0,
      image = "../textures/ladrilho2.png",
      imagewidth = 82,
      imageheight = 82,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 1,
      tiles = {}
    },
    {
      name = "sofa",
      firstgid = 2,
      tilewidth = 408,
      tileheight = 132,
      spacing = 0,
      margin = 0,
      image = "../textures/sofa.png",
      imagewidth = 408,
      imageheight = 132,
      tileoffset = {
        x = 0,
        y = 132
      },
      properties = {},
      terrains = {},
      tilecount = 1,
      tiles = {}
    },
    {
      name = "barata",
      firstgid = 3,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      image = "../textures/barata.png",
      imagewidth = 32,
      imageheight = 32,
      tileoffset = {
        x = 0,
        y = 32
      },
      properties = {},
      terrains = {},
      tilecount = 1,
      tiles = {}
    },
    {
      name = "vassoura2",
      firstgid = 4,
      tilewidth = 93,
      tileheight = 279,
      spacing = 0,
      margin = 0,
      image = "../textures/vassoura2.png",
      imagewidth = 93,
      imageheight = 279,
      tileoffset = {
        x = -46,
        y = 279
      },
      properties = {},
      terrains = {},
      tilecount = 1,
      tiles = {}
    },
    {
      name = "pizza",
      firstgid = 5,
      tilewidth = 58,
      tileheight = 72,
      spacing = 0,
      margin = 0,
      image = "../textures/pizza.png",
      imagewidth = 290,
      imageheight = 74,
      tileoffset = {
        x = 0,
        y = 72
      },
      properties = {},
      terrains = {},
      tilecount = 5,
      tiles = {}
    },
    {
      name = "maca",
      firstgid = 10,
      tilewidth = 30,
      tileheight = 47,
      spacing = 0,
      margin = 0,
      image = "../textures/maca.png",
      imagewidth = 150,
      imageheight = 47,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 5,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Camada de Tiles 1",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      }
    },
    {
      type = "objectgroup",
      name = "obstacles",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 872,
          y = 814.667,
          width = 408,
          height = 132,
          rotation = 180,
          gid = 2,
          visible = true,
          properties = {
            ["obstacle"] = true
          }
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 314.667,
          y = 652.667,
          width = 408,
          height = 132,
          rotation = 270,
          gid = 2,
          visible = true,
          properties = {
            ["obstacle"] = true
          }
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1044,
          y = 256.667,
          width = 408,
          height = 132,
          rotation = 90,
          gid = 2,
          visible = true,
          properties = {
            ["obstacle"] = true
          }
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 474.665,
          y = 88.6667,
          width = 408,
          height = 132,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {
            ["obstacle"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      name = "player",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 348,
          y = 754.667,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "vassouras",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 655.333,
          y = 445.667,
          width = 93,
          height = 279,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1147.33,
          y = 127,
          width = 93,
          height = 279,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288.667,
          y = 247,
          width = 93,
          height = 279,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "food",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48.3333,
          y = 221.333,
          width = 58,
          height = 72,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 755,
          y = 409.333,
          width = 58,
          height = 72,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 291,
          y = 84,
          width = 58,
          height = 72,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 978.333,
          y = 801.667,
          width = 30,
          height = 47,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1091.67,
          y = 885.667,
          width = 30,
          height = 47,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1000.33,
          y = 125.333,
          width = 58,
          height = 72,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1188.33,
          y = 728,
          width = 58,
          height = 72,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80.3333,
          y = 844,
          width = 58,
          height = 72,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 505.667,
          y = 358.667,
          width = 58,
          height = 72,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 538.333,
          y = 563,
          width = 30,
          height = 47,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 742.333,
          y = 320.333,
          width = 30,
          height = 47,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 123.667,
          y = 105.667,
          width = 30,
          height = 47,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66.3333,
          y = 472.333,
          width = 30,
          height = 47,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1191.67,
          y = 147,
          width = 30,
          height = 47,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 437,
          y = 917.667,
          width = 30,
          height = 47,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
